# Generated by Django 3.2.7 on 2022-11-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=30)),
                ('value', models.IntegerField()),
                ('currency', models.CharField(max_length=20)),
            ],
        ),
    ]
