# Generated by Django 3.2.7 on 2022-11-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.IntegerField(default=None, max_length=30),
        ),
    ]
